# Approximate Bayesian Computation model 
# Predicting the probability of elephant survivorship at the Babile Elephant Sancutary in the next 50 years 

library(dplyr)
library(fishualize)
set.seed(0)

# ------- 1: Scenario A ------ 
eleExt <- function ( initialYear, finalYear, growthRate, popInitial, poachDeaths ) 
{
  # this is where we will store the populations each year
  populations = rep(0, 1 + finalYear - initialYear)
  # the first element is the initial population
  populations[1] = popInitial
  # for all the other years....
  for (year in 2:length(populations)) 
  { 
    populations[year] = populations[year-1] * (1 + growthRate) - runif(n=1,min=poachDeaths/2,
                                                                       max = poachDeaths*2)
  }
  # return the vector
  return(populations)
}

eleExt(initialYear=2004,finalYear=2021,growthRate=.058,popInitial=324,poachDeaths=2)



##### simulations
NUMBER_OF_SIMULATIONS <- 100000
##### parameters to try
poachDeaths <- runif(NUMBER_OF_SIMULATIONS,max=64,min=3)
growthRate <- runif(NUMBER_OF_SIMULATIONS, max = 0.07, min = 0.02)
popInitial<- runif(NUMBER_OF_SIMULATIONS, max = 324+50, min = 324-50)

## create a data frame with all the parameters
all_parameters<-
  data.frame(
    poachDeaths=poachDeaths,
    growthRate=growthRate,
    popInitial=popInitial
  ) %>%
  ### assign to each an id (just their row number)
  mutate(id=row_number())

head(all_parameters)

### run the model for each parameter and store all their steps (most of which will be then thrown away, but oh well)
all_runs<-
  all_parameters %>%
  ### for each row
  rowwise() %>%
  ## create a new data frame containing
  do(
    data.frame(
      ## the id (the row number) of the parameters used
      id = .$id,
      #### the simulated years, all the way from 2004 to 2065
      year = 2004:2065,
      #### the number of elephants at each year as generated by eleExt 
      simulated =
        eleExt(initialYear = 2004,finalYear = 2065,
               growthRate = .$growthRate,
               popInitial = .$popInitial,
               poachDeaths = .$poachDeaths))
  ) 
## take the runs and make sure the number of elephants is never negative
all_runs<-
  all_runs %>% ungroup() %>%
  mutate(
    simulated = pmax(simulated,0)
  ) %>%
  ## also change the to elefants
  rename(elephants=simulated)

## take the rows for which 2015 numbers were acceptable
good_simulations<- 
  all_runs %>%
  filter(year==2015) %>%
  filter( elephants > (237-24) & elephants <(237+24))
## get the row number of the parameter data-base associated with the successes
good_simulations<- 
  good_simulations %>% pull(id)
## these are the ones that made it:
nrow(good_simulations)

## tag them
all_runs<-
  all_runs %>%
  mutate(accepted = id %in% good_simulations) %>%
  mutate(accepted = factor(accepted,levels=c(FALSE,TRUE),labels=c("Rejected","Accepted")))

ggplot(
  all_runs %>%
  filter(year>=2004,year<=2015) 
) +
  geom_line(aes(x=year,y=elephants,col=accepted,group=id,alpha=accepted)) +
  scale_alpha_manual(values = c(0.005,1),guide=FALSE) +
  scale_color_manual(name="Simulation",labels=c("Rejected","Accepted"),
                     values = c("red","blue")) +
  annotate("segment",x=2015,xend=2015,y=237-24,yend=237+24,col="green",lwd=2) +
  ggtitle("Accepted and Rejected Runs")  +
  ylab("Number of Elephants") +
  xlab("Simulated Year") +
  theme_light(20) 



#take a look at the accepted parameters
good_parameters<-
  all_parameters %>%
  filter(id %in% good_simulations)
  

library(tidyverse)
all_parameters %>% select(-id) %>%
  gather() %>%
  ggplot() +
  geom_histogram(aes(x=value),fill="black",col="grey")  +
  facet_wrap(~key,scales = "free") +
  ggtitle("Prior")
#interesting thing is that poach deaths become normally distributed
good_parameters %>% select(-id) %>%
  gather() %>%
  ggplot() +
  geom_histogram(aes(x=value),fill="black",col="grey")  +
  facet_wrap(~key,scales = "free") +
  ggtitle("Posterior")


ggplot(
  all_runs %>%
    filter(accepted=="Accepted") %>%
    filter(year>=2004) 
) +
  geom_line(aes(x=year,y=elephants,group=id),alpha=.05) +
  annotate("segment",x=2015,xend=2015,y=237-24,yend=237+24,col="green",lwd=2) +
  ## you can remove this if you want
  geom_smooth(aes(x=year,y=elephants)) +
  coord_cartesian(ylim=c(0,450)) +
  ggtitle("Business as usual projections")  +
  ylab("Number of Elephants") +
  xlab("Simulated Year") +
  theme_light(20) 





# probability of survival within x years
all_runs %>%
  filter(accepted=="Accepted") %>%
  filter(year %in% c(2025,2040,2065)) %>%
  group_by(year) %>%
  summarise(survival = sum(elephants>0)/n())

#### optimistic

## first, let's take all simulations up until 2015
## rename them to initial pop
start_2015<-
  all_runs %>%
  filter(accepted=="Accepted") %>%
  filter(year==2015) %>%
  select(id,elephants) %>%
  rename(popInitial = elephants)

## join them with the parameter list: we will use the 2015 elephants as popInitial now
start_2015<-left_join(start_2015,
          all_parameters %>% select(-popInitial))

## make it optimistic 
start_optimistic<-
  start_2015 %>%
  mutate(poachDeaths=poachDeaths*(1-.5))


optimistic_runs<-
  start_optimistic %>%
  ### for each row
  rowwise() %>%
  ## create a new data frame containing
  do(
    data.frame(
      ## the id (the row number) of the parameters used
      id = .$id,
      #### the simulated years, all the way from 2004 to 2065
      year = 2015:2065,
      #### the number of elephants at each year as generated by eleExt 
      elephants =
        eleExt(initialYear = 2015,finalYear = 2065,
               growthRate = .$growthRate,
               popInitial = .$popInitial,
               poachDeaths = .$poachDeaths))
  ) 

policy_runs<-
  bind_rows(
optimistic_runs %>%
  mutate(policy="Elephant killings reduced by half") %>%
  mutate(elephants = pmax(elephants,0)),
all_runs %>%
  filter(accepted=="Accepted") %>%
  mutate(policy="Current trends")
)
ggplot(
  policy_runs 
) +
  geom_line(aes(x=year,y=elephants,group=interaction(id,policy),col=policy),alpha=0.05) +
  #geom_line(aes(x=year,y=elephants,group=id),alpha=.05,col="orange",data=optimistic_runs) +
  annotate("segment",x=2015,xend=2015,y=237-24,yend=237+24,col="green",lwd=2) +
  ## you can remove this if you want
  geom_smooth(aes(x=year,y=elephants,group=policy,lty=policy),col="black") +
  coord_cartesian(ylim=c(0,450)) +
  ggtitle("Scenario A: Elephant numbers over time")  +
  ylab("Number of Elephants") +
  xlab("Simulated Year") +
  theme_light(20) + 
  theme(legend.title = element_blank()) +
  guides(colour = guide_legend(nrow = 3))


optimistic_runs %>%
  filter(year %in% c(2025,2040,2065)) %>%
  group_by(year) %>%
  summarise(survival = sum(elephants>0)/n())


# ------- 1: Scenario B ------ 
#### we will collect into a vector which years are spike and which aren't
generate_spike_years<- function(initialYear,
                                finalYear,
                                spike_prob=0.15,
                                spike_duration_in_years=3){
  #start the vector assuming all years are NOT spike years
  is_spike_year = rep(FALSE, 1 + finalYear - initialYear)
  #loop with a while
  year<-1
  while(year<length(is_spike_year)){
    #if it's a spike year
    if(runif (n=1)<spike_prob)
    {
      #remember this year as spike year
      is_spike_year[year]<-TRUE
      #also remember the next years as spike years
      for(i in 2:spike_duration_in_years)
      {
        year<-year+1
        is_spike_year[year]<-TRUE
      }
    }
    
    #moving on!
    year<-year+1
  }
  
  return(is_spike_year)
}

library(tidyverse)
generate_spike_years(2000,2100,spike_prob = 0.15,
                     spike_duration_in_years = 3) %>% 
  plot(type="h")



eleExt <- function ( initialYear, 
                     finalYear, 
                     growthRate, 
                     popInitial, 
                     poachDeaths, 
                     spike_min=21,
                     spike_max=64,
                     spike_prob=0.15,
                     spike_duration_in_years=3) 
{
  #compute ahead of time which years will be spiky
  spike_years<-generate_spike_years(2000,2100,
                                    spike_prob = spike_prob,
                                    spike_duration_in_years = spike_duration_in_years)
  # this is where we will store the populations each year
  populations = rep(0, 1 + finalYear - initialYear)
  # the first element is the initial population
  populations[1] = popInitial
  # for all the other years....
  for (year in 2:length(populations)) 
  { 
    # x = rand number [0,1]
    x = runif(n=1,min=0,max=1)
    if (spike_years[year] == FALSE) {
      populations[year] = populations[year-1] * (1 + growthRate) - runif(n=1,min=poachDeaths/2,
                                                                         max = poachDeaths*2)
    }
    else {
      #fixed spike mortality
      populations[year] = populations[year-1] * (1 + growthRate) - runif(n=1,min=spike_min,
                                                                         max = spike_max)
    }
  }
  # return the vector
  return(populations)
}


##### simulations
NUMBER_OF_SIMULATIONS <- 100000
##### parameters to try
poachDeaths <- runif(NUMBER_OF_SIMULATIONS,max=13,min=3)
growthRate <- runif(NUMBER_OF_SIMULATIONS, max = 0.07, min = 0.02)
popInitial<- runif(NUMBER_OF_SIMULATIONS, max = 324+50, min = 324-50)

## create a data frame with all the parameters
all_parameters<-
  data.frame(
    poachDeaths=poachDeaths,
    growthRate=growthRate,
    popInitial=popInitial
  ) %>%
  ### assign to each an id (just their row number)
  mutate(id=row_number())

head(all_parameters)

### run the model for each parameter and store all their steps (most of which will be then thrown away, but oh well)
all_runs<-
  all_parameters %>%
  ### for each row
  rowwise() %>%
  ## create a new data frame containing
  do(
    data.frame(
      ## the id (the row number) of the parameters used
      id = .$id,
      #### the simulated years, all the way from 2004 to 2065
      year = 2004:2065,
      #### the number of elephants at each year as generated by eleExt 
      simulated =
        eleExt(initialYear = 2004,finalYear = 2065,
               growthRate = .$growthRate,
               popInitial = .$popInitial,
               poachDeaths = .$poachDeaths,
               spike_min=21,
               spike_max=64,
               spike_prob=0.15,
               spike_duration_in_years=3))
  ) 
## take the runs and make sure the number of elephants is never negative
all_runs<-
  all_runs %>% ungroup() %>%
  mutate(
    simulated = pmax(simulated,0)
  ) %>%
  ## also change the to elefants
  rename(elephants=simulated)

## take the rows for which 2015 numbers were acceptable
good_simulations<- 
  all_runs %>%
  filter(year==2015) %>%
  filter( elephants > (237-24) & elephants <(237+24))
## get the row number of the parameter data-base associated with the successes
good_simulations<- 
  good_simulations %>% pull(id)
## these are the ones that made it:
nrow(good_simulations)

## tag them
all_runs<-
  all_runs %>%
  mutate(accepted = id %in% good_simulations) %>%
  mutate(accepted = factor(accepted,levels=c(FALSE,TRUE),labels=c("Rejected","Accepted")))

ggplot(
  all_runs %>%
    filter(year>=2004,year<=2015) 
) +
  geom_line(aes(x=year,y=elephants,col=accepted,group=id,alpha=accepted)) +
  scale_alpha_manual(values = c(0.005,1),guide=FALSE) +
  scale_color_manual(name="Simulation",labels=c("Rejected","Accepted"),
                     values = c("red","blue")) +
  annotate("segment",x=2015,xend=2015,y=237-24,yend=237+24,col="green",lwd=2) +
  ggtitle("Accepted and Rejected Runs")  +
  ylab("Number of Elephants") +
  xlab("Simulated Year") +
  theme_light(20) 



#take a look at the accepted parameters
good_parameters<-
  all_parameters %>%
  filter(id %in% good_simulations)


library(tidyverse)
all_parameters %>% select(-id) %>%
  gather() %>%
  ggplot() +
  geom_histogram(aes(x=value),fill="black",col="grey")  +
  facet_wrap(~key,scales = "free") +
  ggtitle("Prior")
#interesting thing is that poach deaths become normally distributed
good_parameters %>% select(-id) %>%
  gather() %>%
  ggplot() +
  geom_histogram(aes(x=value),fill="black",col="grey")  +
  facet_wrap(~key,scales = "free") +
  ggtitle("Posterior")


ggplot(
  all_runs %>%
    filter(accepted=="Accepted") %>%
    filter(year>=2004) 
) +
  geom_line(aes(x=year,y=elephants,group=id),alpha=.05) +
  annotate("segment",x=2015,xend=2015,y=237-24,yend=237+24,col="green",lwd=2) +
  ## you can remove this if you want
  geom_smooth(aes(x=year,y=elephants)) +
  coord_cartesian(ylim=c(0,450)) +
  ggtitle("Business as usual projections")  +
  ylab("Number of Elephants") +
  xlab("Simulated Year") +
  theme_light(20) 


# probability of survival within x years
all_runs %>%
  filter(accepted=="Accepted") %>%
  filter(year %in% c(2025,2040,2065)) %>%
  group_by(year) %>%
  summarise(survival = sum(elephants>0)/n())





#### 0% chance of spike

## first, let's take all simulations up until 2015
## rename them to initial pop
start_2015<-
  all_runs %>%
  filter(accepted=="Accepted") %>%
  filter(year==2015) %>%
  select(id,elephants) %>%
  rename(popInitial = elephants)

## join them with the parameter list: we will use the 2015 elephants as popInitial now
start_2015<-left_join(start_2015,
                      all_parameters %>% select(-popInitial))

## make it optimistic 
start_optimistic<-
  start_2015 


optimistic_runs<-
  start_optimistic %>%
  ### for each row
  rowwise() %>%
  ## create a new data frame containing
  do(
    data.frame(
      ## the id (the row number) of the parameters used
      id = .$id,
      #### the simulated years, all the way from 2004 to 2065
      year = 2015:2065,
      #### the number of elephants at each year as generated by eleExt 
      elephants =
        eleExt(initialYear = 2015,finalYear = 2065,
               growthRate = .$growthRate,
               popInitial = .$popInitial,
               poachDeaths = .$poachDeaths,
               spike_prob=0))
  ) 



optimistic_runs %>%
  filter(year %in% c(2025,2040,2065)) %>%
  group_by(year) %>%
  summarise(survival = sum(elephants>0)/n())



#### 0% chance of spike and 50% reduction in elephant killings

## first, let's take all simulations up until 2015
## rename them to initial pop
start_2015_2<-
  all_runs %>%
  filter(accepted=="Accepted") %>%
  filter(year==2015) %>%
  select(id,elephants) %>%
  rename(popInitial = elephants)

## join them with the parameter list: we will use the 2015 elephants as popInitial now
start_2015_2<-left_join(start_2015_2,
                      all_parameters %>% select(-popInitial))

## make it optimistic 
start_optimistic_2<-
  start_2015_2 %>%
  mutate(poachDeaths=poachDeaths*(1-.5))


optimistic_runs_2<-
  start_optimistic_2 %>%
  ### for each row
  rowwise() %>%
  ## create a new data frame containing
  do(
    data.frame(
      ## the id (the row number) of the parameters used
      id = .$id,
      #### the simulated years, all the way from 2004 to 2065
      year = 2015:2065,
      #### the number of elephants at each year as generated by eleExt 
      elephants =
        eleExt(initialYear = 2015,finalYear = 2065,
               growthRate = .$growthRate,
               popInitial = .$popInitial,
               poachDeaths = .$poachDeaths,
               spike_prob=0))
  ) 


optimistic_runs_2 %>%
  filter(year %in% c(2025,2040,2065)) %>%
  group_by(year) %>%
  summarise(survival = sum(elephants>0)/n())


# Graphs
policy_runs<-
  bind_rows(
    all_runs %>%
      filter(accepted=="Accepted") %>%
      mutate(policy="Current trends"),
    optimistic_runs %>%
      mutate(policy="0% chance of spike") %>%
      mutate(elephants = pmax(elephants,0)),
    optimistic_runs_2 %>%
      mutate(policy="0% chance of spike \n and elephant killings \n reduced by half") %>%
      mutate(elephants = pmax(elephants,0))
  )
policy_runs$policy <- factor(policy_runs$policy, levels = c("Current trends", "0% chance of spike", "0% chance of spike \n and elephant killings \n reduced by half"))
ggplot(
  policy_runs 
) +
  geom_line(aes(x=year,y=elephants,group=interaction(id,policy),col=policy),alpha=0.05) +
  #geom_line(aes(x=year,y=elephants,group=id),alpha=.05,col="orange",data=optimistic_runs) +
  annotate("segment",x=2015,xend=2015,y=237-24,yend=237+24,col="green",lwd=2) +
  ## you can remove this if you want
  geom_smooth(aes(x=year,y=elephants,group=policy,lty=policy),col="black") +
  coord_cartesian(ylim=c(0,450)) +
  ggtitle("Scenario B: Elephant numbers over time")  +
  ylab("Number of Elephants") +
  xlab("Simulated Year") +
  theme_light(28) + 
  #facet_wrap(~policy) + 
  #theme(legend.position = "none")
  theme(legend.title = element_blank(), legend.key.height=unit(2, "cm")) 

